# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Deploy API and ETL pipeline to production

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write
  repository-projects: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy_prod:
    name: Deploy API to production

    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://anteaterapi.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-and-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run database migrations
        working-directory: ./packages/db
        run: pnpm run migrate

      - name: Deploy API to production
        working-directory: ./apps/api
        run: pnpm run deploy --route anteaterapi.com/*

      - name: Deploy ETL pipeline to production
        run: pnpm --filter "./apps/data-pipeline/**" run deploy

      - name: Deploy Key Manager/Dashboard if present
        run: pnpm --filter "./apps/key-manager/**" run deploy;
